# Generated by Django 3.2.7 on 2021-09-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
