# Generated by Django 3.2.7 on 2021-09-12 13:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20210912_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_liked',
            field=models.CharField(blank=True, choices=[('True', 'LIKE'), ('False', 'UNLIKE')], default='False', max_length=6, null=True),
        ),
    ]
