# Generated by Django 3.2.7 on 2021-09-12 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0004_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='event_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
