# Generated by Django 3.2.7 on 2021-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20210912_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.AddField(
            model_name='event',
            name='is_liked',
            field=models.CharField(blank=True, choices=[('True', 'LIKE'), ('False', 'UNLIKE')], default='False', max_length=6, null=True),
        ),
    ]
